### ISSUE TITLE
8.x not supported

### ISSUE THREAD

**Issue by x3rud** [Dev1an/Atem-Simulator#3]
The simulator not support Atem Software Controll 8.0.2

**Comment by Dev1an** [comment]
I have no Atem switcher with me right now so I cannot reverse engineer the new version. If you want this new version to work: please send me a packet dump (using Wireshark for example) of the connection phase using the `Atem Software Control 8.0.2`. So start capturing before you open the Software control app on your computer and stop capturing when the application successfully connected to your Atem.

**Comment by sean-howard** [comment]
Hey @Dev1an ,

I'm getting prompted by the `ATEM Software Control 8.0.3` to run a software update when trying to connect to the simulator running from command line. I assume this is the same issue as the above?

Sadly I don't have a physical switcher with me to do a packet dump either.

![Screenshot](https://user-images.githubusercontent.com/2064434/68736456-ad52f480-061b-11ea-8493-b04048060c38.jpg)

**Comment by Dev1an** [comment]
I skipped 8.0.2 and added support for 8.1.

**Comment by sean-howard** [comment]
I'm still getting the same issue as above from the latest pull from master, running ATEM Software Control 8.1 pointing at `127.0.0.1` with both the commandLineApp and xcodeproj running. Am I missing something? 🤔

**Comment by Dev1an** [comment]
My bad. The commandLineApp was still using the old Swift-Atem package. I have removed it from this repository since it is now included in the [Swift-Atem package](https://github.com/Dev1an/Swift-Atem).
- Download version 1.1.0 (`git clone git@github.com:Dev1an/Swift-Atem.git`)
- Change working directory (`cd Swift-Atem`)
- Run the simulator target (`swift run Simulator`)

The AtemSimulator.xcodeproj should work though. I don't know what happened there. Which package dependencies are you seeing in Xcode under the project navigator? Is it something like this: 
<img width="186" alt="image" src="https://user-images.githubusercontent.com/3158324/69405700-aa818f00-0d00-11ea-9ba7-c0c74738834a.png">


Also: don't run the GUI and the command line app at the same time. They may interfere.

**Comment by sean-howard** [comment]
Hey @Dev1an, sorry for the late response on this, the above worked perfectly 😁

And I got the Xcode project working too now I wasn't trying to run the Mac app and command line tool 😅

FYI, this is what I'm seeing in the package dependencies after the latest clone.

<img width="279" alt="Screenshot 2019-11-30 at 12 12 30" src="https://user-images.githubusercontent.com/2064434/69895475-359afe80-136b-11ea-985a-034d75ab2ad8.png">
